apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

configMapGenerator:
  - name: payment-exception-review-platform-runtime-dashboard
    files:
      - payment-exception-review-platform-runtime.json=dashboards/payment-exception-review-platform-runtime.json

  - name: payment-exception-review-service-health-dashboard
    files:
      - payment-exception-review-service-health.json=staged/reliability/payment-exception-review-service-health.json
  
  - name: kubernetes-networking-namespace-pods-curated
    files:
      - kubernetes-networking-namespace-pods-curated.json=dashboards/kubernetes-networking-namespace-pods-curated.json
  
  - name: prometheus-overview-curated
    files:
      - prometheus-overview-curated.json=dashboards/prometheus-overview-curated.json
generatorOptions:
  disableNameSuffixHash: true
